version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.0

    steps:
      - checkout
      - restore_cache:
          key: Podfile-{{ checksum "Podfile" }}-{{ checksum "Podfile.lock" }}
      - run:
          name: Checkout Git dependencies
          command: |
            git submodule init
            git submodule update
      - run:
          name: Update and install Cocoapods and OCLint
          command: |
            sudo gem install cocoapods --quiet
            pod install --silent
      - run:
          name: Build
          command: |
            xcodebuild -workspace "QuestionKit-iOS.xcworkspace" -scheme "QuestionKit-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 11" | tee xcodebuild.log | xcpretty
      - run:
          name: Test
          command: |
            xcodebuild test -scheme "QuestionKit-iOS" -workspace "QuestionKit-iOS.xcworkspace" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.5,name=iPhone 11" | xcpretty
      - save_cache:
          key: Podfile-{{ checksum "Podfile" }}-{{ checksum "Podfile.lock" }}
          paths:
            - "Pods"
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
